-- 012_create_b2b_agent_warnings.sql
--
-- Creates the b2b_agent_warnings table — structured warnings and reminders
-- generated by B2B agents (primarily Agent F, the cockpit agent) and surfaced
-- to the operator in the B2B cockpit tab. Warnings persist across sessions,
-- can be snoozed or dismissed, and are linked to specific B2B entities.
--
-- Source of truth:
--   docs/business/b2b-data-model-v1.md §Table 5
--   docs/business/b2b-agent-architecture-v1.md §Agent F
--
-- IMPORTANT: This table must remain separate from system_actions (migration 007).
-- Driver-side warnings are computed live from system_actions in lib/warnings.ts.
-- B2B warnings originate from company research state, outreach status, and
-- relationship stage — different sources, different lifecycle. Mixing them into
-- system_actions would pollute the driver-side cockpit with B2B noise and
-- require adding new target_type values for every B2B entity type.
--
-- This migration does not alter any existing table.

CREATE TABLE IF NOT EXISTS b2b_agent_warnings (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- ── Warning classification ───────────────────────────────────────────
  warning_type  TEXT NOT NULL CHECK (warning_type IN (
    'stale_research',           -- enriched target not acted on in 14+ days
    'missed_followup',          -- next_action_date passed with no status change
    'incomplete_barrier_notes', -- approved target has empty barrier_notes
    'high_opp_unactioned',      -- score >= 70 target in outreach_ready for 7+ days
    'pool_too_small_for_draft', -- approved draft ready for Gate 6 but driver pool too small
    'no_contact_found',         -- enriched target has no email and no linkedin_url
    'enterprise_misclassified', -- target scored low-barrier but has >250 employees or procurement page
    'dpa_missing_before_share', -- draft is approved_for_matching but dpa_confirmed = false
    'draft_queue_overflow'      -- more than 10 drafts in drafted/needs_edit simultaneously
  )),

  -- Severity determines display order in cockpit: errors first, then warnings, then reminders.
  severity  TEXT NOT NULL CHECK (severity IN (
    'error',    -- blocks progress or signals a data integrity problem
    'warning',  -- actionable; not blocking but should be resolved soon
    'reminder'  -- informational; low urgency
  )),

  -- ── Entity links ─────────────────────────────────────────────────────
  -- All FKs are nullable — a warning may relate to one or more entities,
  -- or to a system-level condition (e.g. draft_queue_overflow) with no
  -- specific target. ON DELETE SET NULL: warning persists even if the
  -- referenced entity is deleted, for audit purposes.
  target_id        UUID REFERENCES company_research_targets (id) ON DELETE SET NULL,
  relationship_id  UUID REFERENCES pilot_company_relationships (id) ON DELETE SET NULL,
  draft_id         UUID REFERENCES company_need_drafts (id) ON DELETE SET NULL,
  outreach_id      UUID REFERENCES company_outreach_actions (id) ON DELETE SET NULL,

  -- ── Warning content ──────────────────────────────────────────────────
  message          TEXT NOT NULL,  -- human-readable warning description
  suggested_action TEXT,           -- what the operator should do to resolve this warning

  -- ── Resolution lifecycle ─────────────────────────────────────────────
  warning_status  TEXT NOT NULL DEFAULT 'active'
    CHECK (warning_status IN (
      'active',    -- warning is current and visible in cockpit
      'snoozed',   -- operator acknowledged and deferred; re-surfaces after snoozed_until
      'resolved',  -- condition was fixed
      'dismissed'  -- operator decided this warning does not apply
    )),

  -- When warning_status = 'snoozed': re-surface after this timestamp.
  -- Agent F checks this column when computing the active warning list.
  snoozed_until  TIMESTAMPTZ,

  resolved_at    TIMESTAMPTZ,  -- when warning was resolved or dismissed
  resolved_by    TEXT,         -- recruiter identifier
  resolution_note  TEXT,       -- optional note on how the warning was resolved

  -- True when the agent detected the underlying condition resolved itself
  -- without any operator action (e.g. a contact was found for a no_contact_found warning).
  auto_resolved  BOOLEAN NOT NULL DEFAULT false
);

-- ── Indexes ──────────────────────────────────────────────────────────────

-- Cockpit B2B warnings panel: active warnings, errors first.
-- Primary read path for the warning display in the B2B cockpit tab.
CREATE INDEX IF NOT EXISTS idx_baw_active_severity
  ON b2b_agent_warnings (severity, created_at DESC)
  WHERE warning_status = 'active';

-- Snoozed warning revival: find warnings to re-surface after snoozed_until passes.
-- Agent F checks this on each cockpit load cycle.
CREATE INDEX IF NOT EXISTS idx_baw_snoozed
  ON b2b_agent_warnings (snoozed_until ASC)
  WHERE warning_status = 'snoozed';

-- Per-company warning history: all warnings linked to one research target.
CREATE INDEX IF NOT EXISTS idx_baw_target_id
  ON b2b_agent_warnings (target_id, created_at DESC)
  WHERE target_id IS NOT NULL;
