// lib/founderNotifier.ts
//
// Founder notification service for the Logistikklubb Agent.
// Sends a plain-text email to the founder when a scheduled post becomes due.
//
// BOUNDARIES:
//   ✓ Sends email to FOUNDER_NOTIFICATION_EMAIL only
//   ✓ Post text is safe — generated by logistikklubbAgent with no PII
//   ✗ Does NOT include driver PII (name, phone, email)
//   ✗ Does NOT include company names or sensitive business data
//   ✗ Does NOT send to drivers, companies, or the WhatsApp group
//   ✗ Does NOT auto-post to any community channel
//   ✗ Does NOT throw — failure is returned to caller; caller logs it

import { sendEmailViaSmtp, getSmtpFromEmail, getSmtpFromName } from './smtpMailClient';
import {
  sendWhatsAppTemplate,
  getWhatsAppFounderPhone,
  getWhatsAppMaxDaily,
  getWhatsAppTodayCount,
  getWhatsAppTemplateName,
  getWhatsAppTemplateLanguage,
} from './whatsappClient';

// ─── Types ────────────────────────────────────────────────────────────────────

export interface FounderNotifyResult {
  sent:       boolean;
  dry_run:    boolean;
  error:      string | null;
  message_id: string | null;
}

export interface PostDuePayload {
  id:             string;
  day_number:     number;
  title:          string;
  category:       string;
  post_text:      string;
  suggested_time: string | null;
}

// ─── Category labels (Swedish) ────────────────────────────────────────────────

const CATEGORY_LABELS: Record<string, string> = {
  morning_greeting:    'Morgon',
  market_signal:       'Marknad',
  discussion_question: 'Diskussion',
  everyday_logistics:  'Logistikvardag',
  poll:                'Poll',
  weekly_tips:         'Tips',
  soft_cta:            'DriverNord CTA',
};

// ─── Gates ────────────────────────────────────────────────────────────────────

export function isFounderNotificationsEnabled(): boolean {
  return process.env.FOUNDER_NOTIFICATIONS_ENABLED === 'true';
}

export function getFounderNotificationEmail(): string {
  return process.env.FOUNDER_NOTIFICATION_EMAIL ?? '';
}

// ─── Email formatting ─────────────────────────────────────────────────────────

export function formatPostDueEmailSubject(post: PostDuePayload): string {
  return `[Logistikklubb] Dag ${post.day_number} — ${post.title} — Klar att posta`;
}

export function formatPostDueEmailBody(post: PostDuePayload): string {
  const divider  = '────────────────────────────────';
  const catLabel = CATEGORY_LABELS[post.category] ?? post.category;

  return [
    'Hej!',
    '',
    `Din Logistikklubb-post för Dag ${post.day_number} är klar att posta.`,
    '',
    divider,
    `KATEGORI: ${catLabel}`,
    `TITEL: ${post.title}`,
    ...(post.suggested_time ? [`FÖRESLAGEN TID: ${post.suggested_time}`] : []),
    divider,
    '',
    post.post_text,
    '',
    divider,
    '',
    'ÅTGÄRD:',
    '1. Kopiera texten ovan',
    '2. Öppna WhatsApp Logistikklubben',
    '3. Klistra in och skicka',
    '',
    'Hantera inlägget: https://drivernord.com/admin/logistikklubb',
    '',
    'OBS: Inget WhatsApp-meddelande skickades automatiskt.',
    'Manuell posting krävs.',
    '',
    '— DriverNord System',
  ].join('\n');
}

// ─── WhatsApp gates ───────────────────────────────────────────────────────────

export function isFounderWhatsAppEnabled(): boolean {
  return process.env.FOUNDER_WHATSAPP_ENABLED === 'true';
}

// ─── WhatsApp message formatting ──────────────────────────────────────────────
// Builds the body_params array for the logistikklubb_post_due Meta template.
//
// Matching template body (submit to Meta for approval):
//   *[Logistikklubb] Dag {{1}} — {{2}}*
//   {{3}}
//   ▶ Vidarebefordra detta till WhatsApp-gruppen Logistikklubben.
//   🔗 Hantera: drivernord.com/admin/logistikklubb
//   OBS: Inget meddelande skickades automatiskt.
//
// Parameters: {{1}}=day+category, {{2}}=title, {{3}}=post_text (≤850 chars)

const MAX_WA_TEXT_CHARS = 850;

export function formatPostDueWhatsAppParams(post: PostDuePayload): string[] {
  const catLabel = CATEGORY_LABELS[post.category] ?? post.category;
  const dayLine  = `Dag ${post.day_number} — ${catLabel}`;
  const title    = post.title;
  const text     = post.post_text.length > MAX_WA_TEXT_CHARS
    ? post.post_text.slice(0, MAX_WA_TEXT_CHARS - 3) + '...'
    : post.post_text;
  return [dayLine, title, text];
}

// ─── Notify ───────────────────────────────────────────────────────────────────

export async function notifyFounderPostDue(post: PostDuePayload): Promise<FounderNotifyResult> {
  const toEmail = getFounderNotificationEmail();
  if (!toEmail) {
    return { sent: false, dry_run: false, error: 'FOUNDER_NOTIFICATION_EMAIL not configured', message_id: null };
  }

  try {
    const result = await sendEmailViaSmtp({
      to:         toEmail,
      subject:    formatPostDueEmailSubject(post),
      body:       formatPostDueEmailBody(post),
      from_email: getSmtpFromEmail(),
      from_name:  getSmtpFromName(),
    });

    if (result.dry_run) {
      return { sent: false, dry_run: true, error: result.error, message_id: null };
    }
    if (!result.success) {
      return { sent: false, dry_run: false, error: result.error ?? 'SMTP send failed', message_id: null };
    }
    return { sent: true, dry_run: false, error: null, message_id: result.message_id };
  } catch (err) {
    return {
      sent:       false,
      dry_run:    false,
      error:      err instanceof Error ? err.message : String(err),
      message_id: null,
    };
  }
}

// Sends a WhatsApp template message to the founder when a post is due.
// Independent of the email path — both channels can fire on the same post.
// Failure never throws and never blocks markPostDue().
// Gate: FOUNDER_WHATSAPP_ENABLED=true required (false by default in production).
export async function notifyFounderWhatsApp(post: PostDuePayload): Promise<FounderNotifyResult> {
  if (!isFounderWhatsAppEnabled()) {
    return { sent: false, dry_run: true, error: 'FOUNDER_WHATSAPP_ENABLED not set — dry_run', message_id: null };
  }

  const founderPhone = getWhatsAppFounderPhone();
  if (!founderPhone) {
    return { sent: false, dry_run: false, error: 'WHATSAPP_FOUNDER_PHONE not configured', message_id: null };
  }

  // Rate guard — cap WhatsApp notifications per UTC calendar day
  const maxDaily   = getWhatsAppMaxDaily();
  const todayCount = await getWhatsAppTodayCount();
  if (todayCount >= maxDaily) {
    return {
      sent:       false,
      dry_run:    false,
      error:      `WhatsApp daily rate limit reached (${todayCount}/${maxDaily})`,
      message_id: null,
    };
  }

  try {
    const result = await sendWhatsAppTemplate({
      to:            founderPhone,
      template_name: getWhatsAppTemplateName(),
      language:      getWhatsAppTemplateLanguage(),
      body_params:   formatPostDueWhatsAppParams(post),
    });

    if (result.dry_run) {
      return { sent: false, dry_run: true, error: result.error, message_id: null };
    }
    if (!result.success) {
      return { sent: false, dry_run: false, error: result.error ?? 'WhatsApp send failed', message_id: null };
    }
    return { sent: true, dry_run: false, error: null, message_id: result.message_id };
  } catch (err) {
    return {
      sent:       false,
      dry_run:    false,
      error:      err instanceof Error ? err.message : String(err),
      message_id: null,
    };
  }
}
