-- 009_create_company_outreach_actions.sql
--
-- Creates the company_outreach_actions table — storage for every outreach
-- draft generated by the B2B Outreach Draft Agent (Agent C), reviewed by
-- the operator, and (once approved) sent manually by the operator from their
-- own email or LinkedIn account.
--
-- Source of truth:
--   docs/business/b2b-data-model-v1.md §Table 2
--   docs/business/b2b-agent-architecture-v1.md §Agent C
--
-- CRITICAL: This table has no send mechanism. There is no messaging provider
-- call, no webhook, no trigger, and no background process that reads from
-- this table and dispatches a message to a company contact. All sending is
-- performed by the human operator outside the DriverNord system. The sent_at
-- and sent_by columns are populated only when the operator manually confirms
-- they sent the message. This is not equivalent to the driver-side contact
-- agent — company contacts have not consented to automated outreach.
--
-- This migration does not alter any existing table.

CREATE TABLE IF NOT EXISTS company_outreach_actions (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- ── Relation to research target ──────────────────────────────────────
  target_id  UUID NOT NULL REFERENCES company_research_targets (id) ON DELETE CASCADE,

  -- ── Draft content ────────────────────────────────────────────────────
  outreach_type  TEXT NOT NULL CHECK (outreach_type IN (
    'email_first',        -- initial cold email
    'email_followup',     -- follow-up after no reply
    'linkedin_message',   -- LinkedIn message (shorter format)
    'phone_opener',       -- 2–3 sentence phone call opener script
    'objection_response'  -- response to common objections (bemanning confusion, cost, etc.)
  )),

  draft_content  TEXT NOT NULL,   -- the draft message body
  subject_line   TEXT,            -- populated for email_first and email_followup only

  -- Position within a multi-step sequence: 1=first contact, 2=follow-up, etc.
  sequence_position  INTEGER,

  -- ── Approval lifecycle ───────────────────────────────────────────────
  -- Gate 3: operator reviews and approves before manually sending.
  draft_status  TEXT NOT NULL DEFAULT 'drafted'
    CHECK (draft_status IN (
      'drafted',    -- agent produced draft; awaiting operator review
      'needs_edit', -- operator flagged issues; edits required before approval
      'approved',   -- Gate 3 cleared; ready for operator to send manually
      'rejected',   -- operator discarded (wrote their own or decided not to send)
      'sent'        -- operator confirmed they sent the message
    )),

  drafted_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  -- 'agent:outreach_draft' or recruiter ID when written manually
  drafted_by   TEXT        NOT NULL,

  reviewed_at  TIMESTAMPTZ,  -- when operator opened the draft for review
  approved_at  TIMESTAMPTZ,  -- when Gate 3 was cleared
  approved_by  TEXT,         -- recruiter identifier

  rejection_reason  TEXT,    -- why draft was rejected
  edit_notes        TEXT,    -- what was changed from the original draft

  -- ── Human-confirmed send ─────────────────────────────────────────────
  -- These fields are set by the operator confirming an out-of-system send.
  -- They are NEVER set automatically by any agent or background process.
  sent_at       TIMESTAMPTZ,  -- human-confirmed send timestamp
  sent_by       TEXT,         -- recruiter identifier
  send_channel  TEXT CHECK (send_channel IN ('email', 'linkedin', 'phone', 'other')),
  send_context  TEXT          -- e.g. 'sent from personal Gmail, CC joakim.sjolen@trabe.se'
);

-- ── Indexes ──────────────────────────────────────────────────────────────

-- Gate 3 approval queue: drafts awaiting operator review.
-- Primary cockpit read path for outreach draft management.
CREATE INDEX IF NOT EXISTS idx_coa_pending
  ON company_outreach_actions (created_at DESC)
  WHERE draft_status IN ('drafted', 'needs_edit');

-- Per-company draft history: all drafts for one research target.
CREATE INDEX IF NOT EXISTS idx_coa_target_id
  ON company_outreach_actions (target_id, created_at DESC);

-- Confirmed send log: audit of all operator-confirmed sends, newest first.
CREATE INDEX IF NOT EXISTS idx_coa_sent
  ON company_outreach_actions (sent_at DESC)
  WHERE draft_status = 'sent';
